"""
Django settings for puc_refugiados project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent
LOGIN_REDIRECT_URL = '/sistema/refugiados'
LOGOUT_REDIRECT_URL = '/sistema/login'


### Project configuration
# INSERT PROJECT CONFIG INFO HERE
CONFIG_PRODUCTION_URL_LIST = ['refugiados.qa.thalles-sales.dev']
CONFIG_APP_LIST = ['core']
CONFIG_ROOT_URLCONF = 'puc_refugiados.urls'
CONFIG_WSGI_ALIAS = 'puc_refugiados.wsgi.application'



### Base info
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '-')
DEBUG = str(os.environ.get('DEBUG_STATUS', '1')) == '1'

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if DEBUG:
    COMPRESS_ENABLED = False
    ALLOWED_HOSTS = ['localhost', 'refugiados.qa.thalles-sales.dev']
    CSRF_TRUSTED_ORIGINS = ['localhost', 'https://refugiados.qa.thalles-sales.dev']
else:
    COMPRESS_ENABLED = False
    COMPRESS_OFFLINE = True
    COMPRESS_ROOT = os.path.join(BASE_DIR, 'static')
    LIBSASS_OUTPUT_STYLE = 'compressed'
    COMPRESS_FILTERS = {
		'css': [
			'compressor.filters.css_default.CssAbsoluteFilter',
			'compressor.filters.cssmin.rCSSMinFilter'
		],
		'js': [
			'compressor.filters.jsmin.JSMinFilter'
		]
	}
    ALLOWED_HOSTS = CONFIG_PRODUCTION_URL_LIST
    CSRF_TRUSTED_ORIGINS = ['https://refugiados.qa.thalles-sales.dev']



### Project apps and misc configuration
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

	# CSS compressor
    #'compressor',
]

INSTALLED_APPS.extend(CONFIG_APP_LIST)

if not DEBUG:
  MIDDLEWARE = [
      'django.middleware.security.SecurityMiddleware',
      'whitenoise.middleware.WhiteNoiseMiddleware',
      'django.contrib.sessions.middleware.SessionMiddleware',
      'django.middleware.common.CommonMiddleware',
      'django.middleware.csrf.CsrfViewMiddleware',
      'django.contrib.auth.middleware.AuthenticationMiddleware',
      'django.contrib.messages.middleware.MessageMiddleware',
      'django.middleware.clickjacking.XFrameOptionsMiddleware',
  ]
else:
  MIDDLEWARE = [
      'django.middleware.security.SecurityMiddleware',
      'django.contrib.sessions.middleware.SessionMiddleware',
      'django.middleware.common.CommonMiddleware',
      'django.middleware.csrf.CsrfViewMiddleware',
      'django.contrib.auth.middleware.AuthenticationMiddleware',
      'django.contrib.messages.middleware.MessageMiddleware',
      'django.middleware.clickjacking.XFrameOptionsMiddleware',
  ]

ROOT_URLCONF = CONFIG_ROOT_URLCONF

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = CONFIG_WSGI_ALIAS



### Database config
# By default, using Postgresql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PW'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT']
    }
}



### Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



### Internationalization

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


### Static files

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

STATICFILES_FINDERS = (
    # default finders
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders
    #'compressor.finders.CompressorFinder',
)

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
    ('text/es6', 'django_compressor_js.precompilers.BabelCompiler')
)


### EMAIL
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'catedra.svm.puc.minas@gmail.com'
EMAIL_HOST_PASSWORD = 'catSvm211110!'
