# Generated by Django 3.2 on 2021-10-06 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('texto', models.TextField()),
                ('status', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('refugiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.refugiado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('texto', models.TextField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
