# Generated by Django 3.2 on 2021-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acaosolicitacao_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='email_sent_to',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
