# Generated by Django 3.2 on 2021-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_solicitacao_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugiado',
            name='ficha_social',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
