# Generated by Django 3.2.9 on 2021-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211213_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaatendimento',
            name='nome_instituicao',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
